# Generated by Django 4.1.3 on 2023-09-23 07:15

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambikaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colour_colour',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
