# Generated by Django 4.1.3 on 2023-09-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambikaapp', '0002_alter_product_colour_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(through='ambikaapp.ProductSize', to='ambikaapp.size'),
        ),
    ]
