# Generated by Django 4.1.3 on 2023-09-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambikaapp', '0008_orderitem_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedorders',
            name='product',
        ),
        migrations.RemoveField(
            model_name='placedorders',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='placedorders',
            name='size',
        ),
        migrations.AddField(
            model_name='placedorders',
            name='order_items',
            field=models.ManyToManyField(to='ambikaapp.orderitem'),
        ),
    ]
