# Generated by Django 4.1.3 on 2023-09-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambikaapp', '0009_remove_placedorders_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='placedorders',
            name='order_items',
            field=models.ManyToManyField(blank=True, related_name='placed_orders', to='ambikaapp.orderitem'),
        ),
    ]
