# Generated by Django 4.1.5 on 2023-10-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambikaapp', '0010_orderitem_deleted_alter_placedorders_order_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Add-on')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Price of Add-on')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='add_on',
            field=models.ManyToManyField(blank=True, related_name='add_ons', to='ambikaapp.addon'),
        ),
    ]
