# Generated by Django 4.1.5 on 2023-10-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambikaapp', '0011_addon_orderitem_add_on'),
        ('ambikaapp', '0018_alter_product_categories'),
    ]

    operations = [
    ]
